'use client';
import {useState} from 'react';
import {type Invoice,getMetrics,shortMoney,today} from '@/lib/domain';
import {ArrowUpRight,ChartNoAxesCombined} from 'lucide-react';
export const palette=['#7ba886','#bfceac','#dfb78f','#c9c5df','#a1b9bf','#e7d8a9'];
export function CashChart({invoices}:{invoices:Invoice[]}){
 const [period,setPeriod]=useState('six');
 const now=new Date(today()+'T12:00:00Z');
 const data=Array.from({length:period==='six'?6:3},(_,i)=>{const d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-(period==='six'?5:2)+i,1));const month=d.toISOString().slice(0,7);const m=getMetrics(invoices.filter(x=>x.date.startsWith(month)));return{label:new Intl.DateTimeFormat('el-GR',{month:'short'}).format(d),income:m.revenue,expense:m.costs};});
 const max=Math.max(...data.map(d=>d.income),...data.map(d=>d.expense),100000)*1.2;
 const xy=(value:number,i:number)=>[57+i*(610/(data.length-1)),195-value/max*155];
 const line=(field:'income'|'expense')=>data.map((d,i)=>`${i===0?'M':'L'} ${xy(d[field],i).join(' ')}`).join(' ');
 const sum=data.reduce((t,d)=>t+d.income,0);
 return <section className="panel cash-panel"><div className="panel-heading"><div><h3>Έσοδα & έξοδα</h3><p>Η πορεία της επιχείρησής σου</p></div><select aria-label="Περίοδος γραφήματος" value={period} onChange={e=>setPeriod(e.target.value)}><option value="six">Τελευταίοι 6 μήνες</option><option value="three">Τελευταίοι 3 μήνες</option></select></div><div className="chart-overview"><strong>{shortMoney(sum)}</strong><span>καθαρά έσοδα περιόδου</span><div className="chart-legend"><span><i style={{background:'#719b7d'}}/>Έσοδα</span><span><i style={{background:'#d0b18c'}}/>Έξοδα</span></div></div><svg className="cash-chart" viewBox="0 0 700 235" role="img" aria-label={`Έσοδα και έξοδα ανά μήνα: ${data.map(d=>`${d.label}: ${shortMoney(d.income)} έσοδα, ${shortMoney(d.expense)} έξοδα`).join('. ')}`}><defs><linearGradient id="income-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#b9d5bd" stopOpacity=".36"/><stop offset="100%" stopColor="#b9d5bd" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(i=>{const y=195-i*52;return <g key={i}><line x1="57" y1={y} x2="672" y2={y} stroke="var(--line)" strokeDasharray="3 5"/><text x="43" y={y+4} textAnchor="end" fill="var(--muted)" fontSize="10">{Math.round(max*i/3/10000)/10}k</text></g>})}<path d={`${line('income')} L 667 195 L 57 195 Z`} fill="url(#income-fill)"/><path d={line('income')} fill="none" stroke="#789e80" strokeWidth="2.6" strokeLinejoin="round"/><path d={line('expense')} fill="none" stroke="#d0b18c" strokeWidth="2" strokeLinejoin="round" strokeDasharray="5 4"/>{data.map((d,i)=><g key={d.label}><circle cx={xy(d.income,i)[0]} cy={xy(d.income,i)[1]} r="4" fill="var(--card)" stroke="#789e80" strokeWidth="2"><title>{d.label}: {shortMoney(d.income)}</title></circle><text x={xy(0,i)[0]} y="223" textAnchor="middle" fill="var(--muted)" fontSize="11">{d.label}</text></g>)}</svg><div className="panel-foot"><ChartNoAxesCombined size={14}/><span>Καθαρές αξίες χωρίς ΦΠΑ · Ο τρέχων μήνας είναι σε εξέλιξη</span><ArrowUpRight size={14}/></div></section>
}
export function ExpenseChart({invoices}:{invoices:Invoice[]}){
 const grouped=new Map<string,number>();invoices.filter(i=>i.kind==='expense'&&i.status!=='draft').forEach(i=>grouped.set(i.category,(grouped.get(i.category)??0)+i.netCents));
 const rows=[...grouped].sort((a,b)=>b[1]-a[1]);const total=rows.reduce((t,r)=>t+r[1],0);let accumulated=0;
 const gradient=rows.map((r,i)=>{const start=accumulated;accumulated+=r[1]/total*100;return `${palette[i%palette.length]} ${start}% ${accumulated}%`;}).join(',');
 return <section className="panel expense-panel"><div className="panel-heading"><div><h3>Πού πηγαίνουν τα χρήματα</h3><p>Τα έξοδά σου, ανά κατηγορία</p></div></div><div className="donut-wrap"><div className="donut" style={{background:total?`conic-gradient(${gradient})`:'var(--line)'}} role="img" aria-label={rows.map(r=>`${r[0]} ${shortMoney(r[1])}`).join(', ')||'Χωρίς έξοδα'}><div><small>Σύνολο εξόδων</small><strong>{shortMoney(total)}</strong><span>χωρίς ΦΠΑ</span></div></div></div><div className="expense-legend">{rows.length?rows.slice(0,5).map(([label,value],i)=><div key={label}><i style={{background:palette[i%palette.length]}}/><span>{label}</span><b>{Math.round(value/total*100)}%</b></div>):<p className="muted">Τα έξοδα που θα προσθέσεις εμφανίζονται εδώ.</p>}</div></section>
}
