'use client';
import {useState,useRef} from 'react';
import {FileText,Upload,Download,LoaderCircle,ShieldCheck,ArrowRight} from 'lucide-react';
import {Button} from './ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import type {Snapshot} from '@/lib/domain';
import type {ApiCall} from './invoice-form';
import {toast} from 'sonner';
export function UploadDialog({data,api,onClose,onSaved,onReview}:{data:Snapshot;api:ApiCall;onClose:()=>void;onSaved:()=>Promise<void>;onReview:(id:string)=>void}){
 const[file,setFile]=useState<File|null>(null);const[busy,setBusy]=useState(false);const[drag,setDrag]=useState(false);const[error,setError]=useState('');const[fileId,setFileId]=useState<string|null>(null);const input=useRef<HTMLInputElement>(null);
 function choose(f:File|undefined){setError('');setFileId(null);if(!f)return;if(f.size>10*1024*1024||!['application/pdf','image/jpeg','image/png'].includes(f.type)){setError('Επίλεξε PDF, JPG ή PNG έως 10 MB.');return;}setFile(f)}
 async function upload(){if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.set('file',file);const result=await api('/api/uploads',{method:'POST',body:form});setFileId(result.id);await onSaved();toast.success(result.duplicate?'Το αρχείο υπάρχει ήδη στον χώρο σου.':'Το αρχείο αποθηκεύτηκε.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="upload-dialog"><DialogHeader><div className="dialog-icon"><Upload size={24}/></div><DialogTitle>Κάθε αρχείο, στη θέση του.</DialogTitle><DialogDescription>Αποθήκευσε το παραστατικό και συμπλήρωσε τα στοιχεία του.</DialogDescription></DialogHeader><button type="button" className={`dropzone ${drag?'dragging':''}`} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!busy)choose(e.dataTransfer.files[0])}} disabled={busy}><span className="dropzone-icon">{file?<FileText size={30}/>:<Upload size={30}/>}</span><strong>{file?file.name:'Σύρε το αρχείο σου εδώ'}</strong><span>{file?`${(file.size/1024).toFixed(0)} KB · Πάτησε για αλλαγή`:'ή πάτησε για επιλογή από τον υπολογιστή'}</span><small>PDF, JPG, PNG · Έως 10 MB</small></button><input ref={input} type="file" hidden accept="application/pdf,image/jpeg,image/png" onChange={e=>choose(e.target.files?.[0])}/>{error&&<p className="error-message" role="alert">{error}</p>}<div className="dialog-actions">{fileId?<Button onClick={()=>onReview(fileId)}>Καταχώριση στοιχείων<ArrowRight/></Button>:<Button onClick={upload} disabled={!file||busy}>{busy?<LoaderCircle className="spin"/>:<Upload/>}{busy?'Αποθήκευση…':'Αποθήκευση αρχείου'}</Button>}</div>{data.uploads.length>0&&<div className="recent-uploads"><h4>Πρόσφατα αρχεία</h4>{data.uploads.slice(0,6).map(f=><div key={f.id}><FileText size={17}/><span><b>{f.filename}</b><small>{Math.round(f.size/1024)} KB</small></span><a className="icon-button" href={`/api/uploads/${encodeURIComponent(f.id)}?mode=${data.workspace.mode}`} aria-label={`Λήψη ${f.filename}`}><Download size={16}/></a><button className="text-button" onClick={()=>onReview(f.id)}>Καταχώριση</button></div>)}</div>}<p className="upload-privacy"><ShieldCheck size={13}/>Τα αρχεία παραμένουν ιδιωτικά στον χώρο σου.</p></DialogContent></Dialog>
}
